### ISSUE TITLE
Ajouter la possibilité d'exporter les wp_users

### ISSUE THREAD

**Issue by yannbug** [Celyan-SAS/export-wordpress-posts-and-fields-to-csv#1]
- Dans le menu déroulant de la page d'admin du plugin, ajouter "Users"

- Quand on exporte les users, faire un wp-user Query au lieu de WP-Post query.

- Et bien sur on récupère tous les champs ACF associés aux users

- Il faut que ça marche aussi depuis un lien pour exporter directement les users et leurs champs ACF

**Comment by SilverCelyan** [comment]
Ajouter l'export des informations woocommerce si elles existent

**Comment by yannbug** [comment]
Demande différente donc je ferme ce ticket et ouvre un autre :)
